const storeProduct =[
{
    name_prefix:'Васильковый хаплохромис',
    full_name:'Sciaenochromis fryeri',
    size:'>7см',
    description:'',
    images:'',
    prices:'10-13 BYN',
},
{
    name_prefix:'Снежный принц',
    full_name:'Pseudotropheus socolofi albino',
    size:'3см',
    description:'',
    images:'',
    prices:'2.5 BYN',
},
{
    name_prefix:'Анциструс',
    full_name:'Анциструс золотой',
    size:'до 15 см',
    description:'',
    images:'',
    prices:'12 BYN',
},
{
    name_prefix:'Анциструс',
    full_name:'Анциструс простой',
    size:'до 15 см',
    description:'',
    images:'',
    prices:'10 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио телесный',
    size:'от 1,7 см',
    description:'',
    images:'',
    prices:'0.3 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио рерио',
    size:'от 1,7 см',
    description:'',
    images:'',
    prices:'0.5 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио ГЛО  супер красные в белую (полоску,точку)',
    size:'от 1,7 см',
    description:'',
    images:'',
    prices:'0.7 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио ГЛО красные в синию (полоску,точку) ',
    size:'от 1,7 см',
    description:'',
    images:'', 
    prices:'0.7 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио ГЛО синие ',
    size:'от 1,7 см',
    description:'',
    images:'',
    prices:'0.7 BYN',
},
{
    name_prefix:'Данио',
    full_name:' Данио Гло салатовые и изумрудные',
    size:'от 1,7 см',
    description:'',
    images:'',
    prices:'0.7 BYN',
},
{
    name_prefix:'Данио',
    full_name:'Данио жемчужный',
    size:'от 1,7 см',
    description:'',
    images:'',
    prices:'0.8 BYN',
},
{
    name_prefix:'Креветка',
    full_name:' Креветка Неокаридина оранжевая сакура',
    size:'3 см',
    description:'',
    images:'',
    prices:'1.6 BYN',
},
{
    name_prefix:'Тернеция',
    full_name:'Тернеция ГЛО (жёлтая , оранжевая , розовая, суперкрасная)',
    size:'0,5 см',
    description:'',
    images:'',
    prices:'0.5 BYN',
},
{
    name_prefix:'Тернеция',
    full_name:'Тернеция телесная',
    size:'0,5 см',
    description:'',
    images:'',
    prices:'0.5 BYN',
},
{
    name_prefix:'Попугай',
    full_name:'Попугай тигровый сапфировый ',
    size:'2 / 4 см',
    description:'',
    images:'',
    prices:'1 / 2 BYN',
},
{
    name_prefix:'Гуппи',
    full_name:' Гуппи Эндлера Скай Блю',
    size:'2-3 см',
    description:'',
    images:'',
    prices:'1.5 BYN',
},
{
    name_prefix:'Гуппи',
    full_name:'Гуппи Дамбо мозаика',
    size:'3 см',
    description:'',
    images:'',
    prices:'2.2BYN',
},
{
    name_prefix:'Гуппи',
    full_name:'Гуппи Дамбо Драгон Хэд',
    size:'3 см',
    description:'',
    images:'',
    prices:'2.2 BYN',
},
{
    name_prefix:'Гуппи',
    full_name:'Гуппи кои',
    size:'4,5 см',
    description:'',
    images:'',
    prices:'2.2 BYN',
},
{
    name_prefix:'Гурами',
    full_name:'Гурами мраморный с 2-мя точками',
    size:'3 см',
    description:'',
    images:'',
    prices:'0.8 BYN',
},
{
    name_prefix:'Гурами',
    full_name:'Гурами глубокий мрамор',
    size:'3 см',
    description:'',
    images:'',
    prices:'0.8 BYN',
},
{
    name_prefix:'Скалярия',
    full_name:'Скалярия мраморная',
    size:'1 см',
    description:'',
    images:'',
    prices:'1.6 BYN ',
},
{
    name_prefix:'Скалярия',
    full_name:'Скалярия кои красный дьявол ',
    size:'1 см',
    description:'',
    images:'',
    prices:'2 BYN',
},
{
    name_prefix:'Скалярия',
    full_name:'Скалярия фантом красный',
    size:'0,5 см',
    description:'',
    images:'',
    prices:'1.5 BYN',
},
{
    name_prefix:'Скалярия',
    full_name:'Скалярия фантом светлый',
    size:'0,5 см',
    description:'',
    images:'',
    prices:'1.5 BYN',
},
{
    name_prefix:'Ампулярия',
    full_name:'Ампулярия ореховая с жёлтой ногой',
    size:'1 см',
    description:'',
    images:'',
    prices:'0.6 BYN',
},
{
    name_prefix:'Барбус',
    full_name:'Барбус суматранский',
    size:'0,5 / 2 см',
    description:'',
    images:'',
    prices:'0.8 / 1 BYN',
},
{
    name_prefix:'Барбус',
    full_name:'Барбус красный ГЛО с чёрной полосой',
    size:'1 см',
    description:'',
    images:'',
    prices:'1.6BYN',
},
{
    name_prefix:'Барбус',
    full_name:'Барбус одесский',
    size:'1 см',
    description:'',
    images:'',
    prices:'1.6BYN',
},
]